name: FlyUI
version: 1.0
api: [3.0.0, 3.9.0, 3.9.1, 3.9.2, 3.9.3, 3.9.4, 3.9.5, 3.9.6, 3.9.7, 3.9.8, 3.9.9, 4.0.0]
author: zJustMarcel02
main: FlyUI\Main

commands:
 flyui:
  description: "Open the FlyUI!"